version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  web:
    build: .
    env_file:
      - .env.prod
    container_name: shop
    command: ["/app/docker/app.sh"]
    volumes:
      - /var/www/shop/media:/app/media
      - /var/www/shop/static:/app/static
    ports:
      - "6000:6000"
    depends_on:
      - db


  

volumes:
  postgres_data: