# Generated by Django 5.1 on 2024-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offer_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='summa',
        ),
        migrations.AddField(
            model_name='offer',
            name='params',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
