# Generated by Django 5.1 on 2024-08-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offer_summa_offer_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('payment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
